### ISSUE TITLE
undefined method `strip_field' after update to 2.7.0

### ISSUE THREAD

**Issue by seb-sykio** [mikel/mail#1169]
since I updated to 2.7.0, I have this issue :

     

>  Failure/Error: mm = Dkim.sign(mm, :domain => xxx, :selector => 'mail', :private_key => OpenSSL::PKey::RSA.new(xxx))
>       
>       NoMethodError:
>         undefined method `strip_field' for #<Mail::DkimField:0x0000564a55a59bf0 @charset="utf-8">
>       # /xxx/.rvm/gems/ruby-2.4.2@xxx/gems/dkim-1.0.0/lib/mail/dkim_field.rb:12:in `initialize'

might be link with this pull request https://github.com/mikel/mail/pull/766

**Comment by jeremy** [comment]
Thanks for the heads up, @seb-sykio. The [dkim](https://github.com/jhawthorn/dkim) lib will need an update to support Mail 2.7 since it's using Mail::Field internals which have changed. You can file an issue (or a pull request!) on its [GitHub repo](https://github.com/jhawthorn/dkim).
