### ISSUE TITLE
[master] missing charset regression in action mailer

### ISSUE THREAD

**Issue by ahorek** [mikel/mail#1299]
bisected to https://github.com/mikel/mail/commit/404ecdd290f89658fb05da02ea5b6139fd82ebdb

backtrace
```
NoMethodError: undefined method `ascii_only?' for nil:NilClass
/mail/lib/mail/fields/parameter_hash.rb:47:in `block in encoded'
/mail/lib/mail/fields/parameter_hash.rb:46:in `map!'
/mail/lib/mail/fields/parameter_hash.rb:46:in `encoded'
/mail/lib/mail/fields/content_type_field.rb:97:in `encoded'
/mail/lib/mail/field.rb:229:in `method_missing'
/mail/lib/mail/header.rb:182:in `block in encoded'
/mail/lib/mail/header.rb:181:in `each'
/mail/lib/mail/header.rb:181:in `encoded'
/mail/lib/mail/message.rb:1803:in `encoded'
/mail/lib/mail/body.rb:147:in `block in encoded'
/mail/lib/mail/parts_list.rb:31:in `block in collect'
C:/Ruby25-x64/lib/ruby/2.5.0/delegate.rb:349:in `each'
C:/Ruby25-x64/lib/ruby/2.5.0/delegate.rb:349:in `block in delegating_block'
/mail/lib/mail/parts_list.rb:31:in `collect'
/mail/lib/mail/body.rb:147:in `encoded'
/mail/lib/mail/message.rb:1805:in `encoded'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionmailer-5.2.2/lib/action_mailer/base.rb:575:in `set_payload_for_mail'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionmailer-5.2.2/lib/action_mailer/base.rb:559:in `block in deliver_mail'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/actionmailer-5.2.2/lib/action_mailer/base.rb:558:in `deliver_mail'
```
