### PR TITLE
remove duplicate field stripping

### PR DESCRIPTION
**Pull request by grosser**
@bf4 @jeremy @mikel 

calling afield with it's own name seems like a pretty useless feature, removing this breaks ~30 specs, that I'd fix if we decide to go this way ...

https://github.com/mikel/mail/pull/720

Ideally the .to_s would not be necessary, but something in mail or action_mailer passes in a class for content_transfer_encoding :/

fix:

``` Ruby
# https://github.com/mikel/mail/pull/766
Mail::CommonField.class_eval do
  def strip_field(field_name, value)
    value.to_s
  end
end
```

### CODE REVIEW

**Comment by grosser** [comment]
ran into this gain when doing outbound email ... would love to get this merged ... I don't see anyone using this api anyway ...

**Comment by grosser** [comment]
@jeremy rebased, can we get this merged now ?

(using this patch in apps that both handle inbound and outbound mail without any issues since over a year now ... )

**Comment by kjg** [comment]
@grosser You might have to rebase this again

**Comment by grosser** [comment]
done!

File: spec/mail/fields/common/common_field_spec.rb [hunk 1]
```diff
@@ -69,17 +69,8 @@
...
   end
 
-  context "when including the field name" do
-    it "does not strip out content that looks identitcal to the field name" do
-      field = Mail::SubjectField.new("Subject: Subject: for your approval")
-      expect(field.decoded).to eq("Subject: for your approval")
-    end
-  end
-
-  context "when not including the field name" do
```
Comment (kjg) [inline spec/mail/fields/common/common_field_spec.rb]: Can we leave this spec in place?

Comment (grosser) [inline spec/mail/fields/common/common_field_spec.rb]: feels useless to me ... but added it back if that makes you happy ...

Comment (kjg) [inline spec/mail/fields/common/common_field_spec.rb]: Thanks! It's to prove that this bug is still fixed: https://github.com/mikel/mail/pull/719/files

**Comment by jeremy** [comment]
#1111

**Comment by seb-sykio** [comment]
since I updated to 2.7.0, I have this issue :

>       Failure/Error: mm = Dkim.sign(mm, :domain => xxx, :selector => 'mail', :private_key => OpenSSL::PKey::RSA.new(xxx))
>       
>       NoMethodError:
>         undefined method `strip_field' for #<Mail::DkimField:0x0000564a55a59bf0 @charset="utf-8">
>       # /xxx/.rvm/gems/ruby-2.4.2@xxx/gems/dkim-1.0.0/lib/mail/dkim_field.rb:12:in `initialize'
